name: CI

on: [push]
jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [ '10.x', '8.x' ] # todo, see if we can test on "latest"
    steps:
      - uses: actions/checkout@v2
      - run: ./scripts/checkout_submodule
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: yarn install
      - run: yarn lint
      - run: yarn build
      - run: yarn test
      - run: yarn test-with-node
